language: android
addons:
  apt:
    packages:
    - w3m
env:
  global:
  - ANDROID_TARGET=android-22
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=12
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - extra-google-m2repository
  - extra-android-m2repository
  - android-22
  - android-28
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew clean build"
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  ./gradlew publishReleaseApk;
  fi
before_install:
- openssl aes-256-cbc -K $encrypted_054692ad430f_key -iv $encrypted_054692ad430f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
